workflows:
  ios-workflow:
    name: Build and Test iOS
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Set up
        script: |
          echo "Setting up the environment"
      - name: Build
        script: |
          mkdir -p Payload
          xcrun --sdk iphoneos swiftc -target arm64-apple-ios14.0 main.swift -o Payload/BonjourApp
      - name: Package
        script: |
          cd Payload
          zip -r BonjourApp.ipa BonjourApp
    artifacts:
      - Payload/BonjourApp.ipa


    publishing:
      email:
        recipients:
          - muggjosef91@gmail.com
